### ISSUE TITLE
'/usr/local/bin/node' could not be spawned.

### ISSUE THREAD

**Issue by omnichronous** [gouvinb/formatter-jsbeautify#1]
I'm trying to use the package on Windows 7 to format CSS and I get this error despite having added the path to node.exe in my 'path' system variable.

**Comment by gouvinb** [comment]
Hi,

I found the problem, but I didn't really effective solution, `js-beautify` use `node` command and `child_process` does not work properly with node process.
I'll do a quick fix , before really solve the problem.

Thank's for report.
